/-
Copyright (c) 2026 CompPoly Contributors. All rights reserved.
Released under Apache 2.0 license as described in LICENSES/Apache-2.0.txt.
Authors: Derek Sorensen
-/
module

public import CompPoly.Fields.KoalaBear.Ext6.SexticCertData
public import CompPoly.Fields.KoalaBear.Basic
public import Mathlib.Tactic.ComputeDegree

/-!
# Irreducibility of `X^6 + X^3 + 1` over KoalaBear

The sextic `X^6 + X^3 + 1` is the ninth cyclotomic polynomial `Φ₉`, so it is irreducible over
`KoalaBear.Field` exactly because `p` has multiplicative order 6 modulo 9 (`p ≡ 2 mod 9`); its
root is a primitive 9th root of unity. It is the defining polynomial of the degree-6 extension in
`CompPoly/Fields/KoalaBear/Ext6.lean`.

No degree-6 *binomial* does the job, for the same reason as at degree 5 but one step stronger:
`p - 1 = 2^24 · 127`, so `3 ∤ p - 1`, `x ↦ x^3` is a bijection on KoalaBear, and every `W` is a
cube `V^3` — whence `X^6 - W = (X^2 - V)(X^4 + V X^2 + V^2)` factors for *every* `W`.

`Φ₉` is chosen among the irreducible sextics for arithmetic reasons. Every entry of the reduction
table `X^6 … X^10 mod f` is `±1`, so reduction costs no base-field multiplications, and the same
holds for the Frobenius matrix (`θ ↦ θ^2`, since `p ≡ 2 mod 9`). It also exposes the `2`-then-`3`
tower for free: `θ^3` is a primitive cube root of unity, and `F_p(θ^3) = F_p²` because
`Y^2 + Y + 1` is irreducible over KoalaBear.

## Certificates

Degree 6 is *composite*, so Rabin's test needs the trace condition plus one coprimality check per
prime factor of 6 — at `p^3` (for `ℓ = 2`) and `p^2` (for `ℓ = 3`). The collapsed prime-degree
form is not just weaker but unsound here: `(X^3 + X + 4)(X^3 + X - 4)` divides `X^(p^6) - X` and
is coprime to `X^p - X`, so it would pass. The three conditions are discharged by kernel-checked
certificates from `CompPoly/Fields/KoalaBear/Ext6/SexticCertData.lean` (generated by
`scripts/gen_rabin_certificate.py`): a 258-step chain for the trace, 121 and 75 steps plus a
Bézout identity for the two coprimality checks. Each chain is verified by a single kernel
reduction of `CompPoly.RabinCert.runChain` — `Nat` arithmetic only, no `native_decide`.

## Main statements

* `KoalaBear.sexticPoly`: the polynomial `X^6 + X^3 + 1` over `KoalaBear.Field`.
* `KoalaBear.sexticPoly_irreducible`, and the `Fact` instance consumed by
  `CompPoly.Extension.Ext.instField`.
-/

@[expose] public section

namespace KoalaBear

open Polynomial CompPoly.RabinCert

/-- The defining sextic `X^6 + X^3 + 1 = Φ₉` of the degree-6 KoalaBear extension. -/
noncomputable def sexticPoly : Polynomial Field := X ^ 6 + X ^ 3 + C 1

/-- The sextic's little-endian `ℕ`-coefficient encoding. Every coefficient of `Φ₉` is `0` or `1`,
so unlike the quintic this needs no `p - 1` literal to spell a negative coefficient. -/
def sexticL : List ℕ := [1, 0, 0, 1, 0, 0, 1]

/-- The `ℕ`-coefficient encoding denotes the sextic. -/
theorem toPoly_sexticL : toPoly fieldSize sexticL = sexticPoly := by
  show toPoly fieldSize [1, 0, 0, 1, 0, 0, 1] = sexticPoly
  rw [sexticPoly, toPoly_cons, toPoly_cons, toPoly_cons, toPoly_cons, toPoly_cons, toPoly_cons,
    toPoly_cons, toPoly_nil, Nat.cast_zero, Nat.cast_one, map_zero, map_one]
  ring

theorem sexticPoly_natDegree : sexticPoly.natDegree = 6 := by
  rw [sexticPoly]
  compute_degree!

theorem sexticPoly_ne_zero : sexticPoly ≠ 0 := by
  intro h
  have h6 := sexticPoly_natDegree
  rw [h, natDegree_zero] at h6
  exact absurd h6 (by norm_num)

/-!
### The kernel-checked certificates

Each theorem below is one kernel reduction: `runChain` re-verifies every step of the generated
chain (`cur² = q·f + r`, coefficientwise mod `p`), and `chainExp` recomputes the exponent the
chain reaches. `eqModP` checks the Bézout identities for coprimality.
-/

set_option maxRecDepth 60000 in
/-- The 258-step chain for `X^(p^6) mod f` verifies and ends at the residue `X`. -/
theorem sextic_trace_chain :
    runChain fieldSize sexticL [0, 1] SexticCert.traceSteps = some [0, 1] := by rfl

set_option maxRecDepth 60000 in
/-- The trace chain computes the exponent `p^6`. -/
theorem sextic_trace_exp : chainExp 1 SexticCert.traceSteps = fieldSize ^ 6 := by rfl

/-! #### Coprimality with `X^(p^3) - X`, the check for the prime factor `2` of `6` -/

set_option maxRecDepth 60000 in
/-- The 121-step chain for `X^(p^3) mod f` verifies and ends at the recorded residue. -/
theorem sextic_cop3_chain :
    runChain fieldSize sexticL [0, 1] SexticCert.cop3Steps = some SexticCert.cop3Rp := by rfl

set_option maxRecDepth 60000 in
/-- The chain computes the exponent `p^3`. -/
theorem sextic_cop3_exp : chainExp 1 SexticCert.cop3Steps = fieldSize ^ 3 := by rfl

/-- The recorded residue satisfies `cop3Rp = cop3W + X`. -/
theorem sextic_cop3_w_check :
    eqModP fieldSize SexticCert.cop3Rp (addNat SexticCert.cop3W [0, 1]) = true := by rfl

/-- The Bézout identity `cop3U·f + cop3V·cop3W = 1` verifies. -/
theorem sextic_cop3_bezout_check :
    eqModP fieldSize
      (addNat (mulNat SexticCert.cop3U sexticL) (mulNat SexticCert.cop3V SexticCert.cop3W)) [1]
      = true := by rfl

/-! #### Coprimality with `X^(p^2) - X`, the check for the prime factor `3` of `6` -/

set_option maxRecDepth 60000 in
/-- The 75-step chain for `X^(p^2) mod f` verifies and ends at the recorded residue. -/
theorem sextic_cop2_chain :
    runChain fieldSize sexticL [0, 1] SexticCert.cop2Steps = some SexticCert.cop2Rp := by rfl

set_option maxRecDepth 60000 in
/-- The chain computes the exponent `p^2`. -/
theorem sextic_cop2_exp : chainExp 1 SexticCert.cop2Steps = fieldSize ^ 2 := by rfl

/-- The recorded residue satisfies `cop2Rp = cop2W + X`. -/
theorem sextic_cop2_w_check :
    eqModP fieldSize SexticCert.cop2Rp (addNat SexticCert.cop2W [0, 1]) = true := by rfl

/-- The Bézout identity `cop2U·f + cop2V·cop2W = 1` verifies. -/
theorem sextic_cop2_bezout_check :
    eqModP fieldSize
      (addNat (mulNat SexticCert.cop2U sexticL) (mulNat SexticCert.cop2V SexticCert.cop2W)) [1]
      = true := by rfl

/-- Move a proposition across `Fintype.card F = q` while `F`, `q`, and `P` are
still abstract. The large concrete certificate remains a direct argument. -/
set_option maxRecDepth 60000
theorem transport_abstract_card {F : Type*} [Fintype F] {q : ℕ} {P : ℕ → Prop}
    (hcard : Fintype.card F = q) (h : P q) : P (Fintype.card F) := by
  subst hcard
  exact h

/-!
Every `transport_rw_*` theorem below applies the same
`irreducible_of_rabin_degree_six` theorem and the same three certificate
expressions. A condition named by the theorem is discharged by the original
concrete `rw [hcard]`; every other condition crosses the equality inside the
small generic `transport_abstract_card` adapter. The eight variants cover every
subset of zero, one, two, or three concrete certificate transports.
-/

/-- Independent zero-transport control using the upstream wrapper. -/
theorem transport_wrapper_zero : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six_of_card fieldSize hcard sexticPoly_natDegree ?_ ?_ ?_
  · exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- Zero concrete transports; all three equalities cross abstractly. -/
theorem transport_rw_none : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · refine transport_abstract_card hcard ?_
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- One concrete transport, around the 258-step trace certificate. -/
theorem transport_rw_trace : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · rw [hcard]
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- One concrete transport, around the 121-step `q^3` certificate. -/
theorem transport_rw_cop3 : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · refine transport_abstract_card hcard ?_
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- One concrete transport, around the 75-step `q^2` certificate. -/
theorem transport_rw_cop2 : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · refine transport_abstract_card hcard ?_
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- Two concrete transports: trace and `q^3`. -/
theorem transport_rw_trace_cop3 : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · rw [hcard]
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- Two concrete transports: trace and `q^2`. -/
theorem transport_rw_trace_cop2 : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · rw [hcard]
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · refine transport_abstract_card hcard ?_
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- Two concrete transports: `q^3` and `q^2`. -/
theorem transport_rw_cop3_cop2 : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · refine transport_abstract_card hcard ?_
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

/-- Three concrete transports; syntactically the original pre-wrapper proof. -/
theorem transport_rw_all : Irreducible sexticPoly := by
  have hcard : Fintype.card Field = fieldSize := ZMod.card _
  refine irreducible_of_rabin_degree_six sexticPoly_natDegree ?_ ?_ ?_
  · rw [hcard]
    exact dvd_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_trace_chain sextic_trace_exp
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop3_chain sextic_cop3_exp sextic_cop3_w_check sextic_cop3_bezout_check
  · rw [hcard]
    exact isCoprime_X_pow_sub_X_of_runChain toPoly_sexticL sexticPoly_ne_zero
      sextic_cop2_chain sextic_cop2_exp sextic_cop2_w_check sextic_cop2_bezout_check

end KoalaBear
